name: workflow.yml
on:
  push:
    branches: ['release/v[0-9]+.[0-9]+']

jobs:
  # name of jobs
  build-push-docker:

    runs-on: ubuntu-latest
    # does not run pipeline if commit message starts with #NORUN.
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./${{ vars.DOCKER_IMAGE_NAME }}

      # as per docker/build-push-action example
      - name: Build - Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      # as per docker/build-push-action example
      - name: Build - Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      # as per docker/build-push-action example
      - name: Build - Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      # build and push image using docker/build-push-action
#      - name: Build and push to Docker
#        id: build-and-push
#        uses: docker/build-push-action@v5.3.0
#        with:
#          context: ./${{ vars.DOCKER_IMAGE_NAME }}
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USER_ID }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      # build and push image using docker/build-push-action
      - name: Build frontend and push to Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./${{ vars.DOCKER_IMAGE_NAME }}/frontend-react
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_ID }}/${{ vars.DOCKER_IMAGE_NAME }}-frontend-react:${{ github.sha }}

      # build and push image using docker/build-push-action
      - name: Build backend and push to Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./${{ vars.DOCKER_IMAGE_NAME }}/backend-spring
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_ID }}/${{ vars.DOCKER_IMAGE_NAME }}-backend-spring:${{ github.sha }}
